[workspace]
members = [
    "aetheros",         # Cross-platform software stack (like Android)
    "aether-core",      # Shared kernel abstractions
    "abi",
    "user",
    "apps/hello_world",
    "apps/wasm_simple",
    "tools/mkext2"
]
resolver = "2"
