[target.aarch64-unknown-none]
rustflags = [
  "-C", "link-arg=-T/Users/jiaxi/.gemini/antigravity/scratch/AetherOS/apps/wasm_simple/layout.ld",
  "-C", "link-arg=-n"
]

[target.x86_64-unknown-none]
rustflags = [
  "-C", "link-arg=-T/Users/jiaxi/.gemini/antigravity/scratch/AetherOS/apps/wasm_simple/layout.ld",
  "-C", "link-arg=-n",
  "-C", "no-redzone=yes"
]
